{'certificado':'certificados',
           'cancelacion':'otros',
           'cesion de acciones':'otros',
           'cesion de establecimiento':'otros',
           'cesion establecimiento de comercio':'otros',
           'niif':'normas niif',
           'agente':'otros',
           'eventos':'otros',
           'constitucion':'otros',
           'copia documentos':'otros',
           'devolucion dinero':'otros',
           'disminucion capital':'otros',
           'firma digital':'otros',
           'formularios':'otros',
           'ilpc':'otros',
           'ilpp':'otros',
           'ilpv':'otros',
           'ilpv sas':'otros',
           'matricula mercantil':'otros',
           'mutacion':'otros',
           'nombramiento':'actualizacion',
           'plataforma':'problemas plataforma',
           'puntos de atencion':'otros',
           'puntos atencion':'otros',
           'r rup':'otros',
           'reactivacion empresa':'otros',
           'reforma':'otros',
           'registro mercantil':'otros',
           'registro rup':'otros',
           'renovacion mercantil':'otros',
           'renovacion rup':'otros',
           'rnt':'otros',
           'rruneol':'otros',
           'rrup':'otros',
           'rrupf':'otros',
           'rrupv':'otros',
           'rup':'otros',
           'rup renovacion':'otros',
           'rut':'otros',
           'sancion':'otros',
           'traslado domicio':'otros',
           'ciiu':'actualizacion',
           'acceso':'inconveniente clave virtual',
           'años anteriores':'inconveniente clave virtual',
           'beneficios':'otros',
           'reliquidacion':'otros',
           'sancion':'otros',
           'asistencia':'otros'
          }
